from frequency import getAspect
import os

dic = {
'Mortgage':['Loan modification,collection,foreclosure',
             'Loan servicing, payments, escrow account',
             'Credit decision / Underwriting',
             'Application, originator, mortgage broker',
             'Settlement process and costs'],
'Credit reporting':['Improper use of my credit report',
                     'Incorrect information on credit report',
                     'Unable to get credit report/credit score',
                     'Credit monitoring or identity protection',
                     "Credit reporting company's investigation"],
'Student loan':["Can't repay my loan", 'Dealing with my lender or servicer', 'Getting a loan'],
'Debt collection':["Cont'd attempts collect debt not owed",
                    'False statements or representation',
                    'Improper contact or sharing of info',
                    'Communication tactics',
                    'Taking/threatening an illegal action',
                    'Disclosure verification of debt'],
'Credit card':['Other',
                'Identity theft / Fraud / Embezzlement',
                'Late fee',
                'Advertising and marketing',
                'Closing/Cancelling account',
                'Credit determination',
                'Customer service / Customer relations',
                'Credit card protection / Debt protection',
                'Other fee',
                'APR or interest rate',
                'Payoff process',
                'Rewards',
                'Privacy',
                'Credit line increase/decrease',
                'Transaction issue',
                'Billing disputes',
                'Delinquent account',
                'Unsolicited issuance of credit card',
                'Billing statement',
                'Application processing delay',
                'Sale of account',
                'Balance transfer fee',
                'Arbitration',
                'Forbearance / Workout plans',
                'Balance transfer',
                'Overlimit fee',
                'Bankruptcy',
                'Cash advance',
                'Convenience checks',
                'Cash advance fee'],
'Bank account or service':['Deposits and withdrawals',
                            'Account opening, closing, or management',
                            'Using a debit or ATM card',
                            'Problems caused by my funds being low',
                            'Making/receiving payments, sending money'],
'Consumer Loan':['Managing the loan or lease',
                'Taking out the loan or lease',
                'Problems when you are unable to pay',
                'Shopping for a loan or lease',
                'Lender repossessed or sold the vehicle',
                'Applied for loan/did not receive money',
                "Charged fees or interest I didn't expect",
                'Payment to acct not credited',
                "Can't contact lender",
                "Received a loan I didn't apply for",
                "Can't stop charges to bank account",
                'Account terms and changes',
                'Managing the line of credit',
                'Lender sold the property',
                'Shopping for a line of credit',
                'Lender damaged or destroyed vehicle'],
'Money transfers':['Fraud or scam',
                    'Other transaction issues',
                    'Wrong amount charged or received',
                    'Money was not available when promised',
                    'Other service issues',
                    'Incorrect/missing disclosures or info'],
'Payday loan':["Can't contact lender",
                "Charged fees or interest I didn't expect",
                "Received a loan I didn't apply for",
                "Can't stop charges to bank account",
                'Payment to acct not credited',
                'Applied for loan/did not receive money',
                'Charged bank acct wrong day or amt'],
'Prepaid card':['Managing, opening, or closing account',
                'Overdraft, savings or rewards features',
                'Fraud or scam',
                'Unauthorized transactions/trans. issues',
                'Fees',
                'Adding money',
                'Advertising, marketing or disclosures'],
'Other financial service':['Unexpected/Other fees',
                            'Excessive fees',
                            'Fraud or scam',
                            'Lost or stolen money order',
                            'Customer service/Customer relations',
                            'Advertising and marketing',
                            'Disclosures',
                            'Lost or stolen check',
                            'Incorrect exchange rate']
}

root_path = '../result/'
s = getAspect()
for product,aspects in dic.items():
    product_name = "_".join(product.split())
    out_path = root_path + product_name + '/'
    if not os.path.exists(out_path):
        os.makedirs(out_path)
    for aspect in aspects:
        print('save in ' + str(out_path))
        print(aspect)
        #s.run(out_path,product,aspect)

    
